### PR TITLE
Script to create the bulk download ZIP files

### PR DESCRIPTION
**Pull request by simon-20**

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
If someone deletes or reclassifies data such that a country or code previously had data but now doesn't, will the XLSX file be deleted from the disk? Or maybe a blank XLSX file be written?

If not there is a risk that we continue serving old data we should have deleted. 

This isn't a comment on the script, this is a pre existing problem, but if it is an issue then unfortunately the script makes it worse and we need to catch that.

**Comment by simon-20** [comment]
From what I can work out, this may be possible if all of the items for the region or country in question are deleted. It seems that the code doesn't write out empty Excel files where there is no data. Realistically, this means it is a possibility for those country and regions which only contain data from one activity; if that activity was then deleted, then the file wouldn't be deleted, or emptied.

I'll create an issue for this; it belongs on the repo of the `iati-flattener` library, because that's the relevant code.

**Comment by odscjames** [comment]
https://github.com/iati-data-access/data-backend/pull/19

**Comment by ghost** [comment]
https://github.com/iati-data-access/iati-flattener/issues/18

**Pull request merged**
